!supported locales:en,tr
locale=en
!this variable is used to traverse the extension variables below it
fileTypes=text,docx,doc
!these variables are used (in TextFile.java)! Even though they appear grey(depending on your IDE of choice)!
textFileExtensions=txt,md,json,yaml,yml,xml,html,readme,text,plain,ascii,log,java,py,c,cpp,js,css,jsx,go
docxFileExtensions=docx,_docx
docFileExtensions=doc,_doc